using System.IO.Compression;
using System.Net;
using System.Text;
using Microsoft.Extensions.Options;
using Xunit;

namespace TypstRender.Client.Tests;

public sealed class TypstRenderClientTests : IDisposable
{
    private static readonly byte[] FakePdf = Encoding.ASCII.GetBytes("%PDF-fake");

    private readonly string _root;
    private readonly StubHandler _handler = new();

    public TypstRenderClientTests()
    {
        _root = Path.Combine(Path.GetTempPath(), "typst-client-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_root);
    }

    public void Dispose() => Directory.Delete(_root, recursive: true);

    private TypstRenderClient CreateClient(Action<TypstRenderClientOptions>? configure = null)
    {
        var options = new TypstRenderClientOptions
        {
            BaseAddress = new Uri("http://typst-render.test"),
            TemplateRoot = _root,
        };
        configure?.Invoke(options);
        return new TypstRenderClient(new HttpClient(_handler), Options.Create(options));
    }

    private void WriteFile(string relativePath, string content)
    {
        var full = Path.Combine(_root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content);
    }

    [Fact]
    public async Task RenderAsync_PostsScannedBundleWithDataAndConventionalInput()
    {
        WriteFile("shared/styles.typ", "#let primary = blue");
        WriteFile("invoice/main.typ", "#import \"/shared/styles.typ\": primary");
        WriteFile("letter/main.typ", "= Letter");

        var pdf = await CreateClient().RenderAsync("invoice/main.typ", new { number = 42 });

        Assert.Equal(FakePdf, pdf);
        Assert.Equal(
            "?entry=invoice%2Fmain.typ&input=data-path%3D%2Fdata.json",
            _handler.LastRequestUri!.Query);

        var entries = ReadZip(_handler.LastBody!);
        Assert.Equal(["data.json", "invoice/main.typ", "shared/styles.typ"], entries.Keys.OrderBy(k => k, StringComparer.Ordinal));
        Assert.Equal("{\"number\":42}", entries["data.json"]);
    }

    [Fact]
    public async Task RenderAsync_WithoutData_SendsNoDataFileAndNoDataPathInput()
    {
        WriteFile("letter/main.typ", "= Letter");

        await CreateClient().RenderAsync("letter/main.typ");

        Assert.Equal("?entry=letter%2Fmain.typ", _handler.LastRequestUri!.Query);
        Assert.DoesNotContain("data.json", ReadZip(_handler.LastBody!).Keys);
    }

    [Fact]
    public async Task RenderAsync_Request_CarriesExtraInputsAndRootOverride()
    {
        WriteFile("letter/main.typ", "= Letter");

        await CreateClient(o => o.TemplateRoot = null).RenderAsync(new TypstRenderRequest
        {
            TemplateRoot = _root,
            Entry = "letter/main.typ",
            Data = new { x = 1 },
            Inputs = { ["locale"] = "de" },
        });

        Assert.Equal(
            "?entry=letter%2Fmain.typ&input=data-path%3D%2Fdata.json&input=locale%3Dde",
            _handler.LastRequestUri!.Query);
    }

    [Fact]
    public async Task RenderAsync_ExtraFiles_RideAlongWithDiskBundleAndSatisfyTheScanner()
    {
        // The template references a file that never exists on disk — it is
        // generated by the caller at render time and shipped via ExtraFiles.
        WriteFile("report/main.typ", "#image(\"/generated/chart.svg\")");

        await CreateClient().RenderAsync(new TypstRenderRequest
        {
            Entry = "report/main.typ",
            Data = new { title = "Q1" },
            ExtraFiles = { ["generated/chart.svg"] = Encoding.UTF8.GetBytes("<svg/>") },
        });

        var entries = ReadZip(_handler.LastBody!);
        Assert.Equal(
            ["data.json", "generated/chart.svg", "report/main.typ"],
            entries.Keys.OrderBy(k => k, StringComparer.Ordinal));
        Assert.Equal("<svg/>", entries["generated/chart.svg"]);
    }

    [Fact]
    public async Task RenderAsync_ExtraFiles_OverrideOnDiskTemplateFiles()
    {
        WriteFile("report/main.typ", "#image(\"generated/chart.svg\")");
        WriteFile("report/generated/chart.svg", "<svg>placeholder</svg>");

        await CreateClient().RenderAsync(new TypstRenderRequest
        {
            Entry = "report/main.typ",
            ExtraFiles = { ["report/generated/chart.svg"] = Encoding.UTF8.GetBytes("<svg>generated</svg>") },
        });

        var entries = ReadZip(_handler.LastBody!);
        Assert.Equal(["report/generated/chart.svg", "report/main.typ"], entries.Keys.OrderBy(k => k, StringComparer.Ordinal));
        Assert.Equal("<svg>generated</svg>", entries["report/generated/chart.svg"]);
        Assert.Equal(1, CountZipEntries(_handler.LastBody!, "report/generated/chart.svg"));
    }

    [Fact]
    public async Task RenderAsync_ExtraFileCollidingWithDataJson_Throws()
    {
        WriteFile("report/main.typ", "= Hi");

        await Assert.ThrowsAsync<ArgumentException>(() => CreateClient().RenderAsync(new TypstRenderRequest
        {
            Entry = "report/main.typ",
            Data = new { x = 1 },
            ExtraFiles = { ["data.json"] = Encoding.UTF8.GetBytes("{}") },
        }));
    }

    [Fact]
    public async Task RenderAsync_InMemoryFiles_AreShippedAsIs()
    {
        await CreateClient().RenderAsync(new TypstRenderRequest
        {
            Entry = "main.typ",
            Files = new Dictionary<string, byte[]>
            {
                ["main.typ"] = Encoding.UTF8.GetBytes("= Hi"),
            },
        });

        Assert.Equal(["main.typ"], ReadZip(_handler.LastBody!).Keys);
    }

    [Fact]
    public async Task RenderAsync_InMemoryExtraFiles_OverrideSuppliedFiles()
    {
        await CreateClient().RenderAsync(new TypstRenderRequest
        {
            Entry = "main.typ",
            Files = new Dictionary<string, byte[]>
            {
                ["main.typ"] = Encoding.UTF8.GetBytes("#image(\"generated/chart.svg\")"),
                ["generated/chart.svg"] = Encoding.UTF8.GetBytes("<svg>placeholder</svg>"),
            },
            ExtraFiles = { ["generated/chart.svg"] = Encoding.UTF8.GetBytes("<svg>generated</svg>") },
        });

        var entries = ReadZip(_handler.LastBody!);
        Assert.Equal("<svg>generated</svg>", entries["generated/chart.svg"]);
        Assert.Equal(1, CountZipEntries(_handler.LastBody!, "generated/chart.svg"));
    }

    [Fact]
    public async Task RenderAsync_WithoutAnyTemplateRoot_Throws()
    {
        var client = CreateClient(o => o.TemplateRoot = null);

        await Assert.ThrowsAsync<InvalidOperationException>(() => client.RenderAsync("main.typ"));
    }

    [Fact]
    public async Task RenderAsync_ErrorResponse_SurfacesStatusAndDetail()
    {
        WriteFile("letter/main.typ", "= Letter");
        _handler.NextResponse = () => new HttpResponseMessage(HttpStatusCode.UnprocessableEntity)
        {
            Content = new StringContent("error: unknown variable"),
        };

        var ex = await Assert.ThrowsAsync<TypstRenderException>(
            () => CreateClient().RenderAsync("letter/main.typ"));

        Assert.Equal(422, ex.StatusCode);
        Assert.Equal("error: unknown variable", ex.Detail);
    }

    [Fact]
    public async Task RenderAsync_BundleCache_PicksUpTemplateEdits()
    {
        WriteFile("letter/main.typ", "= Before");
        var client = CreateClient();

        await client.RenderAsync("letter/main.typ");
        Assert.Equal("= Before", ReadZip(_handler.LastBody!)["letter/main.typ"]);

        WriteFile("letter/main.typ", "= After (edited)");
        await client.RenderAsync("letter/main.typ");
        Assert.Equal("= After (edited)", ReadZip(_handler.LastBody!)["letter/main.typ"]);
    }

    [Fact]
    public async Task RenderToStreamAsync_ReturnsPdfBytes()
    {
        WriteFile("letter/main.typ", "= Letter");

        using var stream = await CreateClient().RenderToStreamAsync("letter/main.typ");
        using var ms = new MemoryStream();
        await stream.CopyToAsync(ms);

        Assert.Equal(FakePdf, ms.ToArray());
        Assert.Equal("?entry=letter%2Fmain.typ", _handler.LastRequestUri!.Query);
    }

    [Fact]
    public async Task RenderToStreamAsync_ErrorResponse_SurfacesStatusAndDetail()
    {
        WriteFile("letter/main.typ", "= Letter");
        _handler.NextResponse = () => new HttpResponseMessage(HttpStatusCode.UnprocessableEntity)
        {
            Content = new StringContent("error: unknown variable"),
        };

        var ex = await Assert.ThrowsAsync<TypstRenderException>(
            () => CreateClient().RenderToStreamAsync("letter/main.typ"));

        Assert.Equal(422, ex.StatusCode);
        Assert.Equal("error: unknown variable", ex.Detail);
    }

    [Fact]
    public void GetTemplates_ReturnsSortedFolderNamesWithEntry_SkippingOthers()
    {
        WriteFile("invoice/main.typ", "= Invoice");
        WriteFile("letter/main.typ", "= Letter");
        WriteFile("shared/styles.typ", "#let primary = blue"); // no entry -> skipped
        WriteFile("notes.txt", "loose file at root");

        Assert.Equal(["invoice", "letter"], CreateClient().GetTemplates());
    }

    [Fact]
    public void GetTemplates_FindsNestedGroups_AsRootRelativePaths()
    {
        WriteFile("invoice/paid/main.typ", "= Paid");
        WriteFile("invoice/due/main.typ", "= Due");
        WriteFile("letter/main.typ", "= Letter");
        WriteFile("shared/styles.typ", "#let primary = blue"); // no entry -> skipped

        Assert.Equal(["invoice/due", "invoice/paid", "letter"], CreateClient().GetTemplates());
    }

    [Fact]
    public void GetTemplates_WithoutTemplateRoot_Throws()
    {
        var client = CreateClient(o => o.TemplateRoot = null);

        Assert.Throws<InvalidOperationException>(() => client.GetTemplates());
    }

    [Fact]
    public void GetTemplates_MissingRootDirectory_ReturnsEmpty()
    {
        var client = CreateClient(o => o.TemplateRoot = Path.Combine(_root, "does-not-exist"));

        Assert.Empty(client.GetTemplates());
    }

    [Fact]
    public void GetBundleManifest_ReportsImportClosure_WithoutHttpCall()
    {
        WriteFile("shared/styles.typ", "#let primary = blue");
        WriteFile("invoice/main.typ", "#import \"/shared/styles.typ\": primary");
        WriteFile("letter/main.typ", "= Letter");

        var manifest = CreateClient().GetBundleManifest("invoice/main.typ");

        Assert.False(manifest.IsFullFolder);
        Assert.Null(manifest.FullFolderReason);
        Assert.Equal(["invoice/main.typ", "shared/styles.typ"], manifest.Files);
        Assert.Null(_handler.LastRequestUri); // no request was made
    }

    [Fact]
    public void GetBundleManifest_DeclaredExtraFiles_AreToleratedAndNotListed()
    {
        WriteFile("report/main.typ", "#image(\"/generated/chart.svg\")");

        var manifest = CreateClient().GetBundleManifest(
            "report/main.typ", extraFiles: ["generated/chart.svg"]);

        Assert.Equal(["report/main.typ"], manifest.Files);
    }

    [Fact]
    public void GetBundleManifest_DynamicImport_WidensToFullFolder()
    {
        WriteFile("invoice/main.typ", "#let mod = \"parts.typ\"\n#import mod: x");
        WriteFile("invoice/parts.typ", "#let x = 1");
        WriteFile("letter/main.typ", "= Letter");

        var manifest = CreateClient().GetBundleManifest("invoice/main.typ");

        Assert.True(manifest.IsFullFolder);
        Assert.NotNull(manifest.FullFolderReason);
        Assert.Contains("letter/main.typ", manifest.Files);
    }

    private static Dictionary<string, string> ReadZip(byte[] zipBytes)
    {
        using var archive = new ZipArchive(new MemoryStream(zipBytes), ZipArchiveMode.Read);
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var entry in archive.Entries)
        {
            using var reader = new StreamReader(entry.Open());
            result[entry.FullName] = reader.ReadToEnd();
        }

        return result;
    }

    private static int CountZipEntries(byte[] zipBytes, string path)
    {
        using var archive = new ZipArchive(new MemoryStream(zipBytes), ZipArchiveMode.Read);
        return archive.Entries.Count(e => string.Equals(e.FullName, path, StringComparison.Ordinal));
    }

    private sealed class StubHandler : HttpMessageHandler
    {
        public Uri? LastRequestUri { get; private set; }

        public byte[]? LastBody { get; private set; }

        public Func<HttpResponseMessage>? NextResponse { get; set; }

        protected override async Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, CancellationToken cancellationToken)
        {
            LastRequestUri = request.RequestUri;
            LastBody = await request.Content!.ReadAsByteArrayAsync(cancellationToken);

            if (NextResponse is not null)
            {
                return NextResponse();
            }

            return new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new ByteArrayContent(FakePdf),
            };
        }
    }
}
